services:
  php:
    build: ./Apache
    container_name: pagina_web
    ports:
      - "8080:80"
    depends_on:
      - bd 
    volumes:
      - /home/frodriguez/App/Apache:/var/www/html
    networks:
      - red_contenedores
    restart: always

  bd:
    build: ./MySQL
    container_name: bd
    ports:
      - "6033:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: fisigames
    volumes:
      - base_de_datos:/var/lib/mysql
    networks:
      - red_contenedores
    restart: always
volumes:
  base_de_datos:


networks:
  red_contenedores:
